env:
  global:
    - CC_TEST_REPORTER_ID=fea981d6f3cb37192694fa36116b6102a98217e8d22e19359eb84f323d4d3797
before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
  - git config --global url.https://github.com/.insteadOf git://github.com/
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
branches:
  only:
    - master
dist: trusty
language: node_js
node_js:
  - "8.9.1"
notifications:
  email:
    on_success: never
    on_failure: change
addons:
  sauce_connect: true
  chrome: stable
  code_climate:
    repo_token: fea981d6f3cb37192694fa36116b6102a98217e8d22e19359eb84f323d4d3797
before_scripts:
after_success:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter format-coverage --input-type lcov --output reports/coverage/codeclimate.mocha.json reports/coverage/lcov.info
  - ./cc-test-reporter sum-coverage --output reports/coverage/codeclimate.json reports/coverage/codeclimate.*.json
  - ./cc-test-reporter upload-coverage --input reports/coverage/codeclimate.json
